<%-- 
    Document   : terms
    Created on : Apr 21, 2016, 9:53:50 AM
    Author     : Juan
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <jsp:include page="WEB-INF/head/head.jsp" />
    </head>
    <body>
        <h1>Terms and Conditions</h1>
        <h4>Legal</h4>
<h4 id="terms-and-conditions">Terms and Conditions</h4>
<p>Last Updated: January 2, 2016</p>
<h4 id="1-contractual-relationship">1. Contractual Relationship</h4>
<p>These Terms of Use (&quot;<em>Terms</em>&quot;) govern the access or use by you, an individual, from within the United States and its territories and possessions of applications, websites, content, products, and services (the &quot;<em>Services</em>&quot;) made available in the United States and its territories and possessions by QicFix USA, LLC and its subsidiaries and affiliates (collectively, &quot;<em>QicFix</em>&quot;). PLEASE READ THESE TERMS CAREFULLY BEFORE ACCESSING OR USING THE SERVICES. In these Terms, the words &quot;including&quot; and &quot;include&quot; mean &quot;including, but not limited to.&quot;</p>
<p>Your access and use of the Services constitutes your agreement to be bound by these Terms, which establishes a contractual relationship between you and QicFix. If you do not agree to these Terms, you may not access or use the Services. These Terms expressly supersede prior agreements or arrangements with you. QicFix may immediately terminate these Terms or any Services with respect to you, or generally cease offering or deny access to the Services or any portion thereof, at any time for any reason.</p>
<p>Supplemental terms may apply to certain Services, such as policies for a particular event, activity or promotion, and such supplemental terms will be disclosed to you in region-specific disclosures (e.g., a particular city webpage on QicFix.com) or in connection with the applicable Service(s). Supplemental terms are in addition to, and shall be deemed a part of, the Terms for the purposes of the applicable Service(s). Supplemental terms shall prevail over these Terms in the event of a conflict with respect to the applicable Services.</p>
<p>QicFix may amend the Terms related to the Services from time to time. Amendments will be effective upon QicFix's posting of such updated Terms at this location or the amended policies or supplemental terms on the applicable Service(s). Your continued access or use of the Services after such posting constitutes your consent to be bound by the Terms, as amended.</p>
<p>Our collection and use of personal information in connection with the Services is as provided in QicFix's Privacy Policy located at<a href="https://www.uber.com/legal/usa/privacy">www.uber.com/legal/usa/privacy</a>.</p>
<h4 id="2-the-services">2. The Services</h4>
<p>The Services constitute a technology platform that enables users of QicFix's mobile applications or websites provided as part of the Services (each, an &quot;<em>Application</em>&quot;) to arrange and schedule transportation and/or logistics services with third party providers of such services, including independent third party transportation providers and third party logistics providers under agreement with QicFix or certain of QicFix's affiliates (&quot;<em>Third Party Providers</em>&quot;). Unless otherwise agreed by QicFix in a separate written agreement with you, the Services are made available solely for your personal, noncommercial use. YOU ACKNOWLEDGE THAT UBER DOES NOT PROVIDE TRANSPORTATION OR LOGISTICS SERVICES OR FUNCTION AS A TRANSPORTATION CARRIER.</p>
<h5 id="license-">License.</h5>
<p>Subject to your compliance with these Terms, QicFix grants you a limited, non-exclusive, non-sublicensable, revocable, non-transferrable license to: (i) access and use the Applications on your personal device solely in connection with your use of the Services; and (ii) access and use any content, information and related materials that may be made available through the Services, in each case solely for your personal, noncommercial use. Any rights not expressly granted herein are reserved by QicFix and QicFix's licensors.</p>
<h5 id="restrictions-">Restrictions.</h5>
<p>You may not: (i) remove any copyright, trademark or other proprietary notices from any portion of the Services; (ii) reproduce, modify, prepare derivative works based upon, distribute, license, lease, sell, resell, transfer, publicly display, publicly perform, transmit, stream, broadcast or otherwise exploit the Services except as expressly permitted by QicFix; (iii) decompile, reverse engineer or disassemble the Services except as may be permitted by applicable law; (iv) link to, mirror or frame any portion of the Services; (v) cause or launch any programs or scripts for the purpose of scraping, indexing, surveying, or otherwise data mining any portion of the Services or unduly burdening or hindering the operation and/or functionality of any aspect of the Services; or (vi) attempt to gain unauthorized access to or impair any aspect of the Services or its related systems or networks.</p>
<h5 id="provision-of-the-services-">Provision of the Services.</h5>
<p>You acknowledge that portions of the Services may be made available under QicFix's various brands or request options associated with transportation or logistics, including the transportation request brands currently referred to as &quot;<em>QicFix</em>,&quot; &quot;<em>uberX,</em>&quot; &quot;<em>uberXL</em>,&quot; &quot;<em>QicFixBLACK,</em>&quot; &quot;<em>QicFixSUV</em>&quot; and &quot;<em>QicFixLUX</em>&quot; and the logistics request brands currently referred to as &quot;<em>QicFixRUSH</em>,&quot; &quot;<em>QicFixFRESH</em>&quot; and &quot;<em>QicFixEATS</em>&quot;. You also acknowledge that the Services may be made available under such brands or request options by or in connection with: (i) certain of QicFix's subsidiaries and affiliates; or (ii) independent Third Party Providers, including Transportation Network Company drivers, Transportation Charter Permit holders or holders of similar transportation permits, authorizations or licenses.</p>
<h5 id="third-party-services-and-content-">Third Party Services and Content.</h5>
<p>The Services may be made available or accessed in connection with third party services and content (including advertising) that QicFix does not control. You acknowledge that different terms of use and privacy policies may apply to your use of such third party services and content. QicFix does not endorse such third party services and content and in no event shall QicFix be responsible or liable for any products or services of such third party providers. Additionally, Apple Inc., Google, Inc., Microsoft Corporation or BlackBerry Limited will be a third-party beneficiary to this contract if you access the Services using Applications developed for Apple iOS, Android, Microsoft Windows, or Blackberry-powered mobile devices, respectively. These third party beneficiaries are not parties to this contract and are not responsible for the provision or support of the Services in any manner. Your access to the Services using these devices is subject to terms set forth in the applicable third party beneficiary's terms of service.</p>
<h5 id="ownership-">Ownership.</h5>
<p>The Services and all rights therein are and shall remain QicFix's property or the property of QicFix's licensors. Neither these Terms nor your use of the Services convey or grant to you any rights: (i) in or related to the Services except for the limited license granted above; or (ii) to use or reference in any manner QicFix's company names, logos, product and service names, trademarks or services marks or those of QicFix's licensors.</p>
<h4 id="3-your-use-of-the-services">3. Your Use of the Services</h4>
<h5 id="user-accounts-">User Accounts.</h5>
<p>In order to use most aspects of the Services, you must register for and maintain an active personal user Services account (&quot;<em>Account</em>&quot;). You must be at least 18 years of age, or the age of legal majority in your jurisdiction (if different than 18), to obtain an Account. Account registration requires you to submit to QicFix certain personal information, such as your name, address, mobile phone number and age, as well as at least one valid payment method (either a credit card or accepted payment partner). You agree to maintain accurate, complete, and up-to-date information in your Account. Your failure to maintain accurate, complete, and up-to-date Account information, including having an invalid or expired payment method on file, may result in your inability to access and use the Services or QicFix's termination of this Agreement with you. You are responsible for all activity that occurs under your Account, and you agree to maintain the security and secrecy of your Account username and password at all times. Unless otherwise permitted by QicFix in writing, you may only possess one Account.</p>
<h5 id="user-requirements-and-conduct-">User Requirements and Conduct.</h5>
<p>The Service is not available for use by persons under the age of 18. You may not authorize third parties to use your Account, and you may not allow persons under the age of 18 to receive transportation or logistics services from Third Party Providers unless they are accompanied by you. You may not assign or otherwise transfer your Account to any other person or entity. You agree to comply with all applicable laws when using the Services, and you may only use the Services for lawful purposes (<em>e.g.</em>, no transport of unlawful or hazardous materials). You will not in your use of the Services cause nuisance, annoyance, inconvenience, or property damage, whether to the Third Party Provider or any other party. In certain instances you may be asked to provide proof of identity to access or use the Services, and you agree that you may be denied access to or use of the Services if you refuse to provide proof of identity.</p>
<h5 id="text-messaging-">Text Messaging.</h5>
<p>By creating an Account, you agree that the Services may send you informational text (SMS) messages as part of the normal business operation of your use of the Services. You may opt-out of receiving text (SMS) messages from QicFix at any time by texting the word STOP to 89203 from the mobile device receiving the messages. You acknowledge that opting out of receiving text (SMS) messages may impact your use of the Services.</p>
<h5 id="promotional-codes-">Promotional Codes.</h5>
<p>QicFix may, in QicFix's sole discretion, create promotional codes that may be redeemed for Account credit, or other features or benefits related to the Services and/or a Third Party Provider's services, subject to any additional terms that QicFix establishes on a per promotional code basis (&quot;<em>Promo Codes</em>&quot;). You agree that Promo Codes: (i) must be used for the intended audience and purpose, and in a lawful manner; (ii) may not be duplicated, sold or transferred in any manner, or made available to the general public (whether posted to a public form or otherwise), unless expressly permitted by QicFix; (iii) may be disabled by QicFix at any time for any reason without liability to QicFix; (iv) may only be used pursuant to the specific terms that QicFix establishes for such Promo Code; (v) are not valid for cash; and (vi) may expire prior to your use. QicFix reserves the right to withhold or deduct credits or other features or benefits obtained through the use of Promo Codes by you or any other user in the event that QicFix determines or believes that the use or redemption of the Promo Code was in error, fraudulent, illegal, or in violation of the applicable Promo Code terms or these Terms.</p>
<h5 id="user-provided-content-">User Provided Content.</h5>
<p>QicFix may, in QicFix's sole discretion, permit you from time to time to submit, upload, publish or otherwise make available to QicFix through the Services textual, audio, and/or visual content and information, including commentary and feedback related to the Services, initiation of support requests, and submission of entries for competitions and promotions (&quot;<em>User Content</em>&quot;). Any User Content provided by you remains your property. However, by providing User Content to QicFix, you grant QicFix a worldwide, perpetual, irrevocable, transferrable, royalty-free license, with the right to sublicense, to use, copy, modify, create derivative works of, distribute, publicly display, publicly perform, and otherwise exploit in any manner such User Content in all formats and distribution channels now known or hereafter devised (including in connection with the Services and QicFix's business and on third-party sites and services), without further notice to or consent from you, and without the requirement of payment to you or any other person or entity.</p>
<p>You represent and warrant that: (i) you either are the sole and exclusive owner of all User Content or you have all rights, licenses, consents and releases necessary to grant QicFix the license to the User Content as set forth above; and (ii) neither the User Content nor your submission, uploading, publishing or otherwise making available of such User Content nor QicFix's use of the User Content as permitted herein will infringe, misappropriate or violate a third party's intellectual property or proprietary rights, or rights of publicity or privacy, or result in the violation of any applicable law or regulation.</p>
<p>You agree to not provide User Content that is defamatory, libelous, hateful, violent, obscene, pornographic, unlawful, or otherwise offensive, as determined by QicFix in its sole discretion, whether or not such material may be protected by law. QicFix may, but shall not be obligated to, review, monitor, or remove User Content, at QicFix's sole discretion and at any time and for any reason, without notice to you.</p>
<h5 id="network-access-and-devices-">Network Access and Devices.</h5>
<p>You are responsible for obtaining the data network access necessary to use the Services. Your mobile network's data and messaging rates and fees may apply if you access or use the Services from a wireless-enabled device. You are responsible for acquiring and updating compatible hardware or devices necessary to access and use the Services and Applications and any updates thereto. QicFix does not guarantee that the Services, or any portion thereof, will function on any particular hardware or devices. In addition, the Services may be subject to malfunctions and delays inherent in the use of the Internet and electronic communications.</p>
<h4 id="4-payment">4. Payment</h4>
<p>You understand that use of the Services may result in charges to you for the services or goods you receive from a Third Party Provider (&quot;<em>Charges</em>&quot;). After you have received services or goods obtained through your use of the Service, QicFix will facilitate your payment of the applicable Charges on behalf of the Third Party Provider, as such Third Party Provider's limited payment collection agent. Payment of the Charges in such manner shall be considered the same as payment made directly by you to the Third Party Provider. Charges will be inclusive of applicable taxes where required by law. Charges paid by you are final and non-refundable, unless otherwise determined by QicFix. You retain the right to request lower Charges from a Third Party Provider for services or goods received by you from such Third Party Provider at the time you receive such services or goods. QicFix will respond accordingly to any request from a Third Party Provider to modify the Charges for a particular service or good.</p>
<p>All Charges are due immediately and payment will be facilitated by QicFix using the preferred payment method designated in your Account, after which QicFix will send you a receipt by email. If your primary Account payment method is determined to be expired, invalid or otherwise not able to be charged, you agree that QicFix may, as the Third Party Provider's limited payment collection agent, use a secondary payment method in your Account, if available.</p>
<p>As between you and QicFix, QicFix reserves the right to establish, remove and/or revise Charges for any or all services or goods obtained through the use of the Services at any time in QicFix's sole discretion. Further, you acknowledge and agree that Charges applicable in certain geographical areas may increase substantially during times of high demand. QicFix will use reasonable efforts to inform you of Charges that may apply, provided that you will be responsible for Charges incurred under your Account regardless of your awareness of such Charges or the amounts thereof. QicFix may from time to time provide certain users with promotional offers and discounts that may result in different amounts charged for the same or similar services or goods obtained through the use of the Services, and you agree that such promotional offers and discounts, unless also made available to you, shall have no bearing on your use of the Services or the Charges applied to you. You may elect to cancel your request for services or goods from a Third Party Provider at any time prior to such Third Party Provider's arrival, in which case you may be charged a cancellation fee.</p>
<p>This payment structure is intended to fully compensate the Third Party Provider for the services or goods provided. Except with respect to taxicab transportation services requested through the Application, QicFix does not designate any portion of your payment as a tip or gratuity to the Third Party Provider. Any representation by QicFix (on QicFix's website, in the Application, or in QicFix's marketing materials) to the effect that tipping is &quot;voluntary,&quot; &quot;not required,&quot; and/or &quot;included&quot; in the payments you make for services or goods provided is not intended to suggest that QicFix provides any additional amounts, beyond those described above, to the Third Party Provider. You understand and agree that, while you are free to provide additional payment as a gratuity to any Third Party Provider who provides you with services or goods obtained through the Service, you are under no obligation to do so. Gratuities are voluntary. After you have received services or goods obtained through the Service, you will have the opportunity to rate your experience and leave additional feedback about your Third Party Provider.</p>
<h5 id="repair-or-cleaning-fees-">Repair or Cleaning Fees.</h5>
<p>You shall be responsible for the cost of repair for damage to, or necessary cleaning of, Third Party Provider vehicles and property resulting from use of the Services under your Account in excess of normal &quot;wear and tear&quot; damages and necessary cleaning (&quot;<em>Repair or Cleaning</em>&quot;). In the event that a Third Party Provider reports the need for Repair or Cleaning, and such Repair or Cleaning request is verified by QicFix in QicFix's reasonable discretion, QicFix reserves the right to facilitate payment for the reasonable cost of such Repair or Cleaning on behalf of the Third Party Provider using your payment method designated in your Account. Such amounts will be transferred by QicFix to the applicable Third Party Provider and are non-refundable.</p>
<h4 id="5-disclaimers-limitation-of-liability-indemnity-">5. Disclaimers; Limitation of Liability; Indemnity.</h4>
<h5 id="disclaimer-">DISCLAIMER.</h5>
<p>THE SERVICES ARE PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE.&quot; UBER DISCLAIMS ALL REPRESENTATIONS AND WARRANTIES, EXPRESS, IMPLIED, OR STATUTORY, NOT EXPRESSLY SET OUT IN THESE TERMS, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN ADDITION, UBER MAKES NO REPRESENTATION, WARRANTY, OR GUARANTEE REGARDING THE RELIABILITY, TIMELINESS, QUALITY, SUITABILITY, OR AVAILABILITY OF THE SERVICES OR ANY SERVICES OR GOODS REQUESTED THROUGH THE USE OF THE SERVICES, OR THAT THE SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE. UBER DOES NOT GUARANTEE THE QUALITY, SUITABILITY, SAFETY OR ABILITY OF THIRD PARTY PROVIDERS. YOU AGREE THAT THE ENTIRE RISK ARISING OUT OF YOUR USE OF THE SERVICES, AND ANY SERVICE OR GOOD REQUESTED IN CONNECTION THEREWITH, REMAINS SOLELY WITH YOU, TO THE MAXIMUM EXTENT PERMITTED UNDER APPLICABLE LAW.</p>
<h5 id="limitation-of-liability-">LIMITATION OF LIABILITY.</h5>
<p>UBER SHALL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, PUNITIVE, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, LOST DATA, PERSONAL INJURY, OR PROPERTY DAMAGE RELATED TO, IN CONNECTION WITH, OR OTHERWISE RESULTING FROM ANY USE OF THE SERVICES, EVEN IF UBER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. UBER SHALL NOT BE LIABLE FOR ANY DAMAGES, LIABILITY OR LOSSES ARISING OUT OF: (i) YOUR USE OF OR RELIANCE ON THE SERVICES OR YOUR INABILITY TO ACCESS OR USE THE SERVICES; OR (ii) ANY TRANSACTION OR RELATIONSHIP BETWEEN YOU AND ANY THIRD PARTY PROVIDER, EVEN IF UBER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. UBER SHALL NOT BE LIABLE FOR DELAY OR FAILURE IN PERFORMANCE RESULTING FROM CAUSES BEYOND UBER'S REASONABLE CONTROL. YOU ACKNOWLEDGE THAT THIRD PARTY TRANSPORTATION PROVIDERS PROVIDING TRANSPORTATION SERVICES REQUESTED THROUGH SOME REQUEST BRANDS MAY OFFER RIDESHARING OR PEER-TO-PEER TRANSPORTATION SERVICES AND MAY NOT BE PROFESSIONALLY LICENSED OR PERMITTED. IN NO EVENT SHALL UBER'S TOTAL LIABILITY TO YOU IN CONNECTION WITH THE SERVICES FOR ALL DAMAGES, LOSSES AND CAUSES OF ACTION EXCEED FIVE HUNDRED U.S. DOLLARS (US $500).</p>
<p>UBER'S SERVICES MAY BE USED BY YOU TO REQUEST AND SCHEDULE TRANSPORTATION, GOODS, OR LOGISTICS SERVICES WITH THIRD PARTY PROVIDERS, BUT YOU AGREE THAT UBER HAS NO RESPONSIBILITY OR LIABILITY TO YOU RELATED TO ANY TRANSPORTATION, GOODS OR LOGISTICS SERVICES PROVIDED TO YOU BY THIRD PARTY PROVIDERS OTHER THAN AS EXPRESSLY SET FORTH IN THESE TERMS.</p>
<p>THE LIMITATIONS AND DISCLAIMER IN THIS SECTION 5 DO NOT PURPORT TO LIMIT LIABILITY OR ALTER YOUR RIGHTS AS A CONSUMER THAT CANNOT BE EXCLUDED UNDER APPLICABLE LAW.</p>
<h5 id="indemnity-">Indemnity.</h5>
<p>You agree to indemnify and hold QicFix and its officers, directors, employees, and agents harmless from any and all claims, demands, losses, liabilities, and expenses (including attorneys' fees), arising out of or in connection with: (i) your use of the Services or services or goods obtained through your use of the Services; (ii) your breach or violation of any of these Terms; (iii) QicFix's use of your User Content; or (iv) your violation of the rights of any third party, including Third Party Providers.</p>
<h4 id="6-dispute-resolution">6. Dispute Resolution</h4>
<h5 id="arbitration-">Arbitration.</h5>
<p>You agree that any dispute, claim or controversy arising out of or relating to these Terms or the breach, termination, enforcement, interpretation or validity thereof or the use of the Services (collectively, &quot;<em>Disputes</em>&quot;) will be settled by binding arbitration between you and QicFix, except that each party retains the right to bring an individual action in small claims court and the right to seek injunctive or other equitable relief in a court of competent jurisdiction to prevent the actual or threatened infringement, misappropriation or violation of a party's copyrights, trademarks, trade secrets, patents or other intellectual property rights. You acknowledge and agree that you and QicFix are each waiving the right to a trial by jury or to participate as a plaintiff or class in any purported class action or representative proceeding. Further, unless both you and QicFix otherwise agree in writing, the arbitrator may not consolidate more than one person's claims, and may not otherwise preside over any form of any class or representative proceeding. If this specific paragraph is held unenforceable, then the entirety of this &quot;Dispute Resolution&quot; section will be deemed void. Except as provided in the preceding sentence, this &quot;Dispute Resolution&quot; section will survive any termination of these Terms.</p>
<h5 id="arbitration-rules-and-governing-law-">Arbitration Rules and Governing Law.</h5>
<p>The arbitration will be administered by the American Arbitration Association (&quot;<em>AAA</em>&quot;) in accordance with the Commercial Arbitration Rules and the Supplementary Procedures for Consumer Related Disputes (the &quot;<em>AAA Rules</em>&quot;) then in effect, except as modified by this &quot;Dispute Resolution&quot; section. (The AAA Rules are available at <a href="http://www.adr.org/arb_med">www.adr.org/arb_med</a> or by calling the AAA at 1-800-778-7879.) The Federal Arbitration Act will govern the interpretation and enforcement of this Section.</p>
<h5 id="arbitration-process-">Arbitration Process.</h5>
<p>A party who desires to initiate arbitration must provide the other party with a written Demand for Arbitration as specified in the AAA Rules. (The AAA provides a form Demand for Arbitration at<a href="http://www.adr.org/aaa/ShowPDF?doc=ADRSTG_004175">www.adr.org/aaa/ShowPDF?doc=ADRSTG_004175</a> and a separate form for California residents at <a href="http://www.adr.org/aaa/ShowPDF?doc=ADRSTG_015822">www.adr.org/aaa/ShowPDF?doc=ADRSTG_015822</a>.) The arbitrator will be either a retired judge or an attorney licensed to practice law in the state of California and will be selected by the parties from the AAA's roster of consumer dispute arbitrators. If the parties are unable to agree upon an arbitrator within seven (7) days of delivery of the Demand for Arbitration, then the AAA will appoint the arbitrator in accordance with the AAA Rules.</p>
<h5 id="arbitration-location-and-procedure-">Arbitration Location and Procedure.</h5>
<p>Unless you and QicFix otherwise agree, the arbitration will be conducted in the county where you reside. If your claim does not exceed $10,000, then the arbitration will be conducted solely on the basis of documents you and QicFix submit to the arbitrator, unless you request a hearing or the arbitrator determines that a hearing is necessary. If your claim exceeds $10,000, your right to a hearing will be determined by the AAA Rules. Subject to the AAA Rules, the arbitrator will have the discretion to direct a reasonable exchange of information by the parties, consistent with the expedited nature of the arbitration.</p>
<h5 id="arbitrator-s-decision-">Arbitrator's Decision.</h5>
<p>The arbitrator will render an award within the time frame specified in the AAA Rules. The arbitrator's decision will include the essential findings and conclusions upon which the arbitrator based the award. Judgment on the arbitration award may be entered in any court having jurisdiction thereof. The arbitrator's award damages must be consistent with the terms of the &quot;Limitation of Liability&quot; section above as to the types and the amounts of damages for which a party may be held liable. The arbitrator may award declaratory or injunctive relief only in favor of the claimant and only to the extent necessary to provide relief warranted by the claimant's individual claim. If you prevail in arbitration you will be entitled to an award of attorneys' fees and expenses, to the extent provided under applicable law. QicFix will not seek, and hereby waives all rights QicFix may have under applicable law to recover, attorneys' fees and expenses if QicFix prevail in arbitration.</p>
<h5 id="fees-">Fees.</h5>
<p>Your responsibility to pay any AAA filing, administrative and arbitrator fees will be solely as set forth in the AAA Rules. However, if your claim for damages does not exceed $75,000, QicFix will pay all such fees unless the arbitrator finds that either the substance of your claim or the relief sought in your Demand for Arbitration was frivolous or was brought for an improper purpose (as measured by the standards set forth in Federal Rule of Civil Procedure 11(b)).</p>
<h5 id="changes-">Changes.</h5>
<p>Notwithstanding the provisions of the modification-related provisions above, if QicFix changes this &quot;Dispute Resolution&quot; section after the date you first accepted these Terms (or accepted any subsequent changes to these Terms), you may reject any such change by providing QicFix written notice of such rejection by mail or hand delivery to: QicFix USA, LLC, Attn: Dispute Resolutions, 160 Greentree Drive, Suite 101, Dover, DE 19904, or by email from the email address associated with your Account to: <a href="mailto:change-dr@uber.com">change-dr@uber.com</a>, within 30 days of the date such change became effective, as indicated in the &quot;Last update&quot; date above. In order to be effective, the notice must include your full name and clearly indicate your intent to reject changes to this &quot;Dispute Resolution&quot; section. By rejecting changes, you are agreeing that you will arbitrate any Dispute between you and QicFix in accordance with the provisions of this &quot;Dispute Resolution&quot; section as of the date you first accepted these Terms (or accepted any subsequent changes to these Terms).</p>
<h4 id="7-other-provisions">7. Other Provisions</h4>
<h5 id="choice-of-law-">Choice of Law.</h5>
<p>These Terms are governed by and construed in accordance with the laws of the State of California, U.S.A., without giving effect to any conflict of law principles, except as may be otherwise provided in supplemental terms applicable to your region.</p>
<h5 id="claims-of-copyright-infringement-">Claims of Copyright Infringement.</h5>
<p>Claims of copyright infringement should be sent to QicFix's designated agent. Please visit QicFix's web page at <a href="https://www.uber.com/legal/usa/copyright">www.uber.com/legal/usa/copyright</a> for the designated address and additional information.</p>
<h5 id="notice-">Notice.</h5>
<p>QicFix may give notice by means of a general notice on the Services, electronic mail to your email address in your Account, or by written communication sent by first class mail or pre-paid post to your address in your Account. Such notice shall be deemed to have been given upon the expiration of 48 hours after mailing or posting (if sent by first class mail or pre-paid post) or 12 hours after sending (if sent by email). You may give notice to QicFix, with such notice deemed given when received by QicFix, at any time by first class mail or pre-paid post to QicFix USA, LLC, Attn: User Notices - Legal, 160 Greentree Drive, Suite 101, Dover, DE 19904.</p>
<h5 id="general-">General.</h5>
<p>You may not assign these Terms without QicFix's prior written approval. QicFix may assign these Terms without your consent to: (i) a subsidiary or affiliate; (ii) an acquirer of QicFix's equity, business or assets; or (iii) a successor by merger. Any purported assignment in violation of this section shall be void. No joint venture, partnership, employment, or agency relationship exists between you, QicFix or any Third Party Provider as a result of this Agreement or use of the Services. If any provision of these Terms is held to be invalid or unenforceable, such provision shall be struck and the remaining provisions shall be enforced to the fullest extent under law. QicFix's failure to enforce any right or provision in these Terms shall not constitute a waiver of such right or provision unless acknowledged and agreed to by QicFix in writing.</p>
        <jsp:include page="WEB-INF/footer/footer.jsp" />
    </body>
</html>
